apiVersion: v1
kind: Service
metadata:
  name: service-db
  labels:
    app: escuela-db
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: escuela-db